app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication form
Route::get('auth/login','Auth\AuthController@getLogin');
Route::get('auth/reset','Auth\AuthController@getLoginAfterResetPassword');
Route::post('auth/login','Auth\AuthController@postLogin');
Route::get('auth/logout','Auth\AuthController@getLogout');
//

// Registration form
Route::get('auth/register','Auth\AuthController@getRegister');
Route::post('auth/register','Auth\AuthController@postRegister');
//
// Password reset link request
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
//
// Password reset
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');
Route::post('password/reset/{token}', 'Auth\PasswordController@postReset');

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function() {

	Route::get('home', function() {
		return Redirect::route('demands.index');
	});
	
	// DEBUT Route utilisateurs 
	Route::model('users', 'App\User');
	Route::resource('users', 'UserController');

	Route::bind('users', function($value, $route) {
		return App\User::whereEmail($value)->first();
	});
	
	Route::get('modifyPassword', 'UserController@modifyPassword');
	Route::match(['get', 'post'],'updatePwd', function() {
		return view('users.partials.updatePwd');
	});
	// FIN Route utilisateurs
	
	// DEBUT Routes Mairie
	Route::get('council', function() {
    	return View::make('councils.show')->with('council', Session::get('council'));
	});
	
	Route::model('councils', 'App\Council');
	Route::resource('councils', 'CouncilsController');
	// FIN routes mairie
	
	Route::get('account', function() {
		return view('account');
	});
	
	Route::get('modifyAccount', 'UserController@modifyAccount');
	
	Route::get('addLinkFoyer', 'UserController@addLinkFoyer');
	Route::get('deleteLinkFoyer', 'UserController@deleteLinkFoyer');
	
	Route::get('getAssociation', 'UserController@getAssociation');
	Route::get('addLinkAssociation', 'UserController@addLinkAssociation');
	Route::get('deleteLinkAssociation', 'UserController@deleteLinkAssociation');
	
	Route::match(['get', 'post'],'modifyCoord', function() {
		return view('modifyCoord');
	});
	Route::match(['get', 'post'],'modifyAddress', function() {
		return view('modifyAddress');
	});
	
	Route::match(['get', 'post'],'addLinkFoy', function() {
		return view('addLinkFoy');
	});
	Route::match(['get', 'post'],'addLinkAsso', function() {
		return view('addLinkAsso');
	});
	
	Route::get('editHouseMember', function() {
		return view('editHouseMember');
	});
	
	Route::get('editAssociation', function() {
		return view('editAssociation');
	});

	// DEBUT Route des demandes
	Route::model('demands', 'App\Demand');
	Route::resource('demands', 'DemandsController');
	Route::bind('demands', function($value, $route) {
		return App\Demand::whereExternalId($value)->first();
	});
	
	// Liste des motifs lies a un objet
	Route::get('getMotifsFromObject/{id}','DemandsController@getMotifsFromObject');
	
	// Ajout d'un commentaire sur une demande
	Route::get('submitComment', 'DemandsController@submitComment');
	Route::match(['get', 'post'],'addComment', function() {
		return view('demands.partials.addComment');
	});
	// FIN Route des demandes
	
	// Route des evenements
	Route::get('events', function() {
		return view('events');
	});
	
	//Admin
	Route::get('admin', function() {
		return view('admin');
	});

	Route::get('admin2', function() {
		return view('admin2');
	});	

	Route::get('admin3', function() {
		return view('admin2');
	});	

	Route::get('admin4', function() {
		return view('admin2');
	});	

	Route::get('admin5', function() {
		return view('admin2');
	});	
	Route::get('admin6', function() {
		return view('admin2');
	});	
	Route::group(['middleware' => 'admin'], function() {
		Route::model('portalConfigs', 'App\PortalConfig');
		Route::resource('portalConfigs', 'PortalConfigsController');
	});//aaa
	//bbbb
	//cccc
});

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['council_id', 'title', 'lastname', 'firstname', 'email', 'password', 'address', 'zipcode', 'city', 'country', 'women_name', 'engaged_status', 'landline_phone', 'mobile_phone', 'socialsecurity_id', 'birthdate', 'birthplace', 'externalcrm_id','is_admin','is_admin_deca', 'avatar'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
}

app/Http/Controllers/UserController.php
<?php namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB as DB;
use Illuminate\Http\Request;
use Response;

use Davispeixoto\Laravel5Salesforce\Salesforce as Salesforce;
use Illuminate\Config\Repository as Repository;
use Illuminate\Translation\FileLoader;
use Mail;

use App\User as User;

use \stdClass;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Input;
use Redirect;
use Form;

class UserController extends Controller {

	protected $rules = [
		'title' => ['required'],		
		'lastname' => ['required'],	
		'firstname' => ['required'],	
		'email' => ['required'],
	];

	/* Méthode qui met à jour les données de l'utilisateur */
	public function modifyAccount(Request $request) {
		
		$this->validate($request, [
			'landlinephone' => 'numeric|digits:10',
			'mobilephone' => 'numeric|digits:10',
			'email' => 'email|max:255|unique:users',
			'zipcode' => 'numeric|digits:5',
			'address' => 'max:255',
			'city' => 'max:100',
		]);
		
		$configSFDC = session('sfdcConfig');
		$environment = 'local';
		$id = session('userExternalId');
		$config = new Repository($configSFDC, $environment);
		$mySFDC = new Salesforce($config);
		
		$updateDB = array();
		$records = array();
		$records[0] = new stdclass();
		$records[0]->Id = $id;
		$param = false;
		
		if($request->has('sit')) {
			$updateDB += array('engaged_status' => $request->input('sit'));
			$records[0]->Situation_maritale__c = $request->input('sit');
			$param = true;
		}
		if($request->has('bir')) {
			$birthdate_format = date_create_from_format('d/m/Y', $request->input('bir'));
			$birthdate = date_format($birthdate_format, 'Y-m-d');
			$updateDB += array('birthdate' => $birthdate);
			$records[0]->Birthdate = $birthdate;
			$param = true;
		}
		if($request->has('landlinephone')) {
			$updateDB += array('landline_phone' => $request->input('landlinephone'));
			$records[0]->Phone = $request->input('landlinephone');
			$param = true;
		}
		if($request->has('mobilephone')) {
			$updateDB += array('mobile_phone' => $request->input('mobilephone'));
			$records[0]->MobilePhone = $request->input('mobilephone');
			$param = true;
		}
		if($request->has('email')) {
			$updateDB += array('email' => $request->input('email'));
			$records[0]->Email = $request->input('email');
			$param = true;
		}
		if($request->has('address')) {
			$updateDB += array('address' => $request->input('address'));
			$records[0]->Adresse__c = $request->input('address');
			$param = true;
		}
		if($request->has('zipcode')) {
			$updateDB += array('zipcode' => $request->input('zipcode'));
			$records[0]->Code_Postal__c = $request->input('zipcode');
			$param = true;
		}
		if($request->has('city')) {
			$updateDB += array('city' => $request->input('city'));
			$records[0]->Ville__c = $request->input('city');
			$param = true;
		}
		if($request->has('cou')) {
			$updateDB += array('country' => $request->input('cou'));
			$records[0]->Pays__c = $request->input('cou');
			$param = true;
		}
		
		if($param) {
			DB::table('users')->where('externalcrm_id','=',$id)->update($updateDB);
			$mySFDC->sfh->update($records, 'Contact');
		}
		
		return $request->json()->all();
	}
	
	/* Méthode qui modifie le mot de passe de l'utilisateur */
	public function modifyPassword(Request $request) {
		$this->validate($request, [
			'password' => 'required|confirmed|min:8'
		]);
		
		$id = session('userExternalId');
		
		if($request->has('password')) {
			$updateDB = array('password' => bcrypt($request->input('password')));
			DB::table('users')->where('externalcrm_id','=',$id)->update($updateDB);
			
			$email = DB::table('users')->where('externalcrm_id','=',$id)->value('email');
			
			// On envoie un mail
			Mail::send('emails.newpassword', [], function($message) use($email) {
				$message->from(config('mail.from.address'), config('mail.from.name'));
				$message->to($email);
				$message->subject('Réinitialisation de votre mot de passe');
			});	
		}
		return $request->json()->all();
		
	}
	
	/* Méthode qui ajoute un lien entre deux personnes du foyer */
	public function addLinkFoyer(Request $request) {
		
		$this->validate($request, [
			'lastname' => 'required',
			'firstname' => 'required',
			'birthdate' => 'required',
			'typelink' => 'required',
		]);
		
		$configSFDC = session('sfdcConfig');
		$environment = 'local';
		$customerId = session('userExternalId');
		$config = new Repository($configSFDC, $environment);
		$mySFDC = new Salesforce($config);
		
		$foyerId = ' ';
		
		// On remet la date de naissance à son format Salesforce
		$birthdate_format = date_create_from_format('d/m/Y', $request->input('birthdate'));
		$birthdate = date_format($birthdate_format, 'Y-m-d');
		
		// Première étape : on vérifie si l'utilisateur qu'on souhaite ajouter est présent ou pas sur Salesforce
		$accountQuery = "SELECT Id from Contact where FirstName = '" . $request->input('firstname') . "' AND LastName = '" . $request->input('lastname') . "' AND Birthdate = " . $birthdate . "";
		$accountResponse = $mySFDC->sfh->query($accountQuery);
		
		$records = array();
		$records[0] = new stdClass();
		$records[0]->FirstName = $request->input('firstname');
		$records[0]->LastName = $request->input('lastname');
		$records[0]->Birthdate = $birthdate;
		if($request->has('title')) {
			$records[0]->Salutation = $request->input('title');
		}
		if($request->has('birthplace')) {
			$records[0]->Lieu_de_naissance__c = $request->input('birthplace');
		}
		
		if(count($accountResponse->records) == 0) {
			// L'utilisateur n'est pas présent sur Salesforce, on l'ajoute
			$response = $mySFDC->sfh->create($records,'Contact');
			$foyerId = $response[0]->id;
		} else {
			// Le compte existe et on le met à jour avec les données que l'utilisateur a rempli
			$foyerId = $accountResponse->records[0]->Id;
			$records[0]->Id = $foyerId;
			$response = $mySFDC->sfh->update($records,'Contact');
		}
		
		// Seconde étape : on ajoute le lien "Salesforce" entre les deux utilisateurs
		$records_link = array();
		$records_link[0] = new stdClass();
		$records_link[0]->Personne__c = $customerId;
		$records_link[0]->Personne_liee__c = $foyerId;
		$records_link[0]->Foyer__c = true;
		$records_link[0]->Type_de_lien__c = $request->input('typelink');
		
		// Le lien dans l'autre sens est automatiquement créé via un trigger sur Salesforce
		$mySFDC->sfh->create($records_link, 'Lien__c');
		
		return $request->json()->all();
	}
	
	/* Méthode qui supprime un lien entre deux personnes du foyer */
	public function deleteLinkFoyer(Request $request) {
		
		$configSFDC = session('sfdcConfig');
		$environment = 'local';
		$customerId = session('userExternalId');
		$config = new Repository($configSFDC, $environment);
		$mySFDC = new Salesforce($config);

		$contactId = $request->input('idContact');
		
		// Il faut supprimer les deux objets "Lien__c" sur Salesforce car il n'y a pas de trigger de suppression sur Salesforce des liens automatiques
		$linkQuery = "SELECT Id from Lien__c where Personne__r.Id = '" . $customerId . "' AND Personne_liee__r.Id = '" . $contactId . "'";
		$linkResponse = $mySFDC->sfh->query($linkQuery);
		$arrayContactId = array();
		array_push($arrayContactId, $linkResponse->records[0]->Id);
		$mySFDC->sfh->delete($arrayContactId);

		return $request->json()->all();
		
	}
	
	/* Méthode qui récupère la liste des associations présentes sur Salesforce */
	public function getAssociation() {
		
		$configSFDC = session('sfdcConfig');
		$environment = 'local';
		$customerId = session('userExternalId');
		$config = new Repository($configSFDC, $environment);
		$mySFDC = new Salesforce($config);
		
		$assoQuery = "SELECT Id, Name FROM Association__c ORDER BY Name";
		$assoResponse = $mySFDC->sfh->query($assoQuery);
		
		$options = array();
		foreach($assoResponse->records as $record) {
			$options += array($record->Id => $record->Name);
		}
		return Response::json($options);
	}
	
	/* Méthode qui ajoute un nouveau lien entre l'association et la personne */
	public function addLinkAssociation(Request $request) {
		
		$this->validate($request, [
			'id_asso' => 'required',
			'fonction' => 'required',
		]);
		
		$configSFDC = session('sfdcConfig');
		$environment = 'local';
		$id = session('userExternalId');
		$config = new Repository($configSFDC, $environment);
		$mySFDC = new Salesforce($config);
		
		$records = array();
		$records[0] = new stdClass();
		$records[0]->Association__c = $request->input('id_asso');
		$records[0]->Personne__c = $id;
		$records[0]->Fonction__c = $request->input('fonction');
		
		if($request->has('since_asso')) {
			$since_asso_format = date_create_from_format('d/m/Y', $request->input('since_asso'));
			$since_asso = date_format($since_asso_format, 'Y-m-d');
			$records[0]->Depuis_le__c = $since_asso;
		}
		$mySFDC->sfh->create($records, 'Lien_Association_Personne__c');
		
		return $request->json()->all();
	}
	
	/* Méthode qui supprime un lien entre l'association et la personne */
	public function deleteLinkAssociation(Request $request) {
		
		$configSFDC = session('sfdcConfig');
		$environment = 'local';
		$customerId = session('userExternalId');
		$config = new Repository($configSFDC, $environment);
		$mySFDC = new Salesforce($config);
		
		$assoId = $request->input('idAsso');
		
		$linkQuery = "SELECT Id from Lien_Association_Personne__c where Personne__r.Id = '" . $customerId . "' AND Association__r.Id = '" . $assoId . "'";
		$linkResponse = $mySFDC->sfh->query($linkQuery);
		$arrayAssoId = array();
		array_push($arrayAssoId, $linkResponse->records[0]->Id);
		$mySFDC->sfh->delete($arrayAssoId);
		
		return $request->json()->all();
	}

		/**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
		//TODO ne lister ques les utilisateurs du meme council_id pour les admin non deca
		$users = User::all();
		return view('users.index', compact('users'));
    }
	
	/**
     * Show the form for creating a new resource.
     *
     * @return Response

resources/views/users/create.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="users">Utilisateurs</a></li>
			<li><a href="users/create">Nouvel utilisateur</a></li>
		</ol>
	</div>
</div>

{!! Form::model(new App\User, ['route' => ['users.store']]) !!}
	{!! csrf_field() !!}
    @include('users/partials/_form', ['submit_text' => 'Enregistrer'])
{!! Form::close() !!}

@endsection

resources/views/users/edit.blade.php
@extends('layout')
@section('content')
<div id="dialogForm" class="modal fade" role="dialog"></div>

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="users">Utilisateurs</a></li>
			<li><a href="users/{{$User->email or ''}}/edit">{{$User->firstname or ''}} {{$User->lastname or ''}}</a></li>
			
		</ol>
	</div>
</div>

{!! Form::model($User, ['method' => 'PATCH', 'route' => ['users.update', $User->email]]) !!}
	{!! csrf_field() !!}
	@include('users/partials/_form', ['submit_text' => 'Enregistrer'])
{!! Form::close() !!}

<script type="text/javascript">
$(document).ready(function() {
	$("#updatePwd").on("click", function() {
		$('#dialogForm').load('updatePwd #dialogPwd', function(responseTxt, statusTxt, xhr){
			$('#dialogForm').modal('show');
			$.getScript('js/userPwd.js');
		});
	});
});
</script>
@endsection

resources/views/users/index.blade.php
@extends('layout')

@section('content')
<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="users">Utilisateurs</a></li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-users"></i>
					<span>Utilisateurs</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				@if (Session::has('message'))		
					<div class="flash alert-info">			
						<p>{{ Session::get('message') }}</p>		
					</div>	
				@endif
				@if (session('user')->is_admin_deca == 1)
					<center><button type="button" onclick='window.location.href="{{ route('users.create') }}";' class="btn btn-primary btn-sm btn-label-left" id="newUser"><span><i class="fa fa-pencil-square-o"></i></span>Nouvel utilisateur</button></center>
				@endif
				@if ( !$users->count() )
					Aucun utilisateur recens&eacute;e. Veuillez cliquer sur le bouton "Nouvel utilisateur" pour cr&eacute;er un compte.
				@else
					<table id="tableUser" class="table table-striped table-hover table-heading table-datatable dataTable">
						<thead>
							<tr>
								<th></th>
								<th>Pr&eacute;nom</th>
								<th>Nom</th>
								<th>Email</th>
								<th>Administrateur</th>
								@if (session('user')->is_admin_deca == 1)
									<th>Admin Deca</th>
								@endif
							</tr>
						</thead>
						<tbody>
						@foreach( $users as $user )
							<tr>
								<td>
									{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('users.destroy', $user->email))) !!}
									{!! link_to_route('users.edit', 'Modifier', array($user->email), array('class' => 'btn btn-info')) !!}
									@if (session('user')->is_admin_deca == 1)
										{!! Form::submit('Supprimer', array('class' => 'btn btn-danger')) !!}
									@endif
									{!! Form::close() !!}
								</td>
								<td>{{ $user->firstname or ''}}</td>
								<td>{{ $user->lastname or '' }}</td>
								<td>{{ $user->email or '' }}</td>
								<td>{{ $user->is_admin or '' }}</td>
								@if (session('user')->is_admin_deca == 1)
									<td>{{ $user->is_admin_deca or '' }}</td>
								@endif
							</tr>
						@endforeach 
						</tbody>
					</table>
				@endif
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
		$('#tableUser').dataTable( {
		language: {
			processing:     "Traitement en cours...",
			search:         "",
			lengthMenu:     "Afficher _MENU_",
			info:           "Utilisateurs _START_ &agrave; _END_ sur _TOTAL_",
			infoEmpty:      "",
			infoFiltered:   "(filtr&eacute; de _MAX_ utilisateurs au total)",
			infoPostFix:    "",
			loadingRecords: "Chargement en cours...",
			zeroRecords:    "Aucun utilisateur &agrave; afficher",
			emptyTable:     "Aucun utilisateur &agrave; afficher",
			paginate: {
				first:      "Premier",
				previous:   "Pr&eacute;c&eacute;dent",
				next:       "Suivant",
				last:       "Dernier"
			},
			aria: {
				sortAscending:  ": activer pour trier la colonne par ordre croissant",
				sortDescending: ": activer pour trier la colonne par ordre décroissant"
			}
		},
		"aaSorting": [[ 0, "asc" ]],
		"sDom": "<'box-content'<'col-sm-6'f><'col-sm-6 text-right'l><'clearfix'>>rt<'box-content'<'col-sm-6'i><'col-sm-6 text-right'p><'clearfix'>>",
	} );
	$('#tableUser_filter input').attr("placeholder", "Rechercher");
	$('#tableUser_filter input').attr("class", "");
});
</script>

@endsection

resources/views/users/show.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="./home">Accueil</a></li>
			<li><a href="./users">Utilisateurs</a></li>
		</ol>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-8">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-home"></i>
					<span>Utilisateur</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">Utilisateur</h4>
					<p>
						<div class="form-group">
							<label class="col-sm-3 control-label">Civilit&eacute;</label>
							<div class="col-sm-5">
								{{$User->title or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Pr&eacute;nom</label>
							<div class="col-sm-5">
								{{$User->firstname or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Nom</label>
							<div class="col-sm-5">
								{{$User->lastname or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Email</label>
							<div class="col-sm-5">
								{{$User->email or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Code externe CRM</label>
							<div class="col-sm-5">
								{{$User->externalcrm_id or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Administrateur</label>
							<div class="col-sm-5">
								{{$User->is_admin or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Administrateur Deca</label>
							<div class="col-sm-5">
								{{$User->is_admin_deca or ''}}
							</div>
						</div>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
@stop