app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication form
Route::get('auth/login','Auth\AuthController@getLogin');
Route::get('auth/reset','Auth\AuthController@getLoginAfterResetPassword');
Route::post('auth/login','Auth\AuthController@postLogin');
Route::get('auth/logout','Auth\AuthController@getLogout');
//

// Registration form
Route::get('auth/register','Auth\AuthController@getRegister');
Route::post('auth/register','Auth\AuthController@postRegister');
//
// Password reset link request
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
//
// Password reset
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');
Route::post('password/reset/{token}', 'Auth\PasswordController@postReset');

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function() {

	Route::get('home', function() {
		return Redirect::route('demands.index');
	});
	
	// DEBUT Route utilisateurs 
	Route::model('users', 'App\User');
	Route::resource('users', 'UserController');

	Route::bind('users', function($value, $route) {
		return App\User::whereEmail($value)->first();
	});
	
	Route::get('modifyPassword', 'UserController@modifyPassword');
	Route::match(['get', 'post'],'updatePwd', function() {
		return view('users.partials.updatePwd');
	});
	// FIN Route utilisateurs
	
	// DEBUT Routes Mairie
	Route::get('council', function() {
    	return View::make('councils.show')->with('council', Session::get('council'));
	});
	
	Route::model('councils', 'App\Council');
	Route::resource('councils', 'CouncilsController');
	// FIN routes mairie
	
	Route::get('account', function() {
		return view('account');
	});
	
	Route::get('modifyAccount', 'UserController@modifyAccount');
	
	Route::get('addLinkFoyer', 'UserController@addLinkFoyer');
	Route::get('deleteLinkFoyer', 'UserController@deleteLinkFoyer');
	
	Route::get('getAssociation', 'UserController@getAssociation');
	Route::get('addLinkAssociation', 'UserController@addLinkAssociation');
	Route::get('deleteLinkAssociation', 'UserController@deleteLinkAssociation');
	
	Route::match(['get', 'post'],'modifyCoord', function() {
		return view('modifyCoord');
	});
	Route::match(['get', 'post'],'modifyAddress', function() {
		return view('modifyAddress');
	});
	
	Route::match(['get', 'post'],'addLinkFoy', function() {
		return view('addLinkFoy');
	});
	Route::match(['get', 'post'],'addLinkAsso', function() {
		return view('addLinkAsso');
	});
	
	Route::get('editHouseMember', function() {
		return view('editHouseMember');
	});
	
	Route::get('editAssociation', function() {
		return view('editAssociation');
	});

	// DEBUT Route des demandes
	Route::model('demands', 'App\Demand');
	Route::resource('demands', 'DemandsController');
	Route::bind('demands', function($value, $route) {
		return App\Demand::whereExternalId($value)->first();
	});
	
	// Liste des motifs lies a un objet
	Route::get('getMotifsFromObject/{id}','DemandsController@getMotifsFromObject');
	
	// Ajout d'un commentaire sur une demande
	Route::get('submitComment', 'DemandsController@submitComment');
	Route::match(['get', 'post'],'addComment', function() {
		return view('demands.partials.addComment');
	});
	// FIN Route des demandes
	
	// Route des evenements
	Route::get('events', function() {
		return view('events');
	});
	
	//Admin
	Route::get('admin', function() {
		return view('admin');
	});

	Route::get('admin2', function() {
		return view('admin2');
	});	

	Route::get('admin3', function() {
		return view('admin2');
	});	

	Route::get('admin4', function() {
		return view('admin2');
	});	

	Route::get('admin5', function() {
		return view('admin2');
	});	
	Route::get('admin6', function() {
		return view('admin2');
	});	
	Route::group(['middleware' => 'admin'], function() {
		Route::model('portalConfigs', 'App\PortalConfig');
		Route::resource('portalConfigs', 'PortalConfigsController');
	});//aaa
	//bbbb
	//cccc
});

app/Demand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Demand extends Model
{
    /**
	* The database table used by the model.
	*
	* @var string
	*/
	protected $table = 'demands';

	/**
	* The attributes that are mass assignable.
	*
	* @var array
	*/
	protected $fillable = ['council_id', 'contact_id', 'external_id', 'object_id', 'objectLbl', 'motive_id', 'motiveLbl', 'comments', 'status', 'created_date', 'closed_date', 'priority', 'contact_medium'];

	/**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];
	
	protected $guarded = [];
}

resources/views/demands/create.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="demands">Mes demandes</a></li>
			<li><a href="demands/create">Nouvelle demande</a></li>
		</ol>
	</div>
</div>

{!! Form::model(new App\Demand, ['route' => ['demands.store']]) !!}
	{!! csrf_field() !!}
    <div class="row">
	<div class="col-xs-12 col-sm-12 col-md-8">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-pencil-square-o"></i>
					<span>Demande</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">{{$Demand->object or 'Nouvelle demande'}}</h4>
					<input type='hidden' name='portal_id' id='portal_id' value="{{$Demand->portal_id or ''}}" />
					@if (session('user')->is_admin_deca == 1)
						@if ($errors->has('contact_id'))
							<div class="row form-group has-error">
						@else
							<div class="row form-group">
						@endif
						<label class="col-sm-4 col-md-3 control-label">Customer Id *</label>
						<div class="col-sm-8 col-md-5">
								<input type="text" class="form-control"  name="contact_id" id="contact_id" value="{{$Demand->contact_id or session('user')->externalcrm_id}}" />
						</div>
						@if ($errors->has('contact_id'))
							@foreach ($errors->get('contact_id') as $error)
								<small class="help-block col-sm-8 col-sm-offset-3">{{ $error }}</small>
							@endforeach
						@endif
						</div>
					@else
						<input type='hidden' name='contact_id' id='contact_id' value="{{$Demand->contact_id or session('user')->externalcrm_id}}" />
					@endif
					@if (isset($Demand->external_id))
						@if ($errors->has('external_id'))
							<div class="row form-group has-error">
						@else
							<div class="row form-group">
						@endif
							<label class="col-sm-4 col-md-3 control-label">N&deg; demande</label>
							<div class="col-sm-8 col-md-5">
								@if (session('user')->is_admin_deca == 1)
									<input type="text" class="form-control"  name="external_id" id="external_id" value="{{$Demand->external_id or ''}}" />
								@else
									{{$Demand->external_id or ''}}
								@endif
							</div>
							@if ($errors->has('external_id'))
								@foreach ($errors->get('external_id') as $error)
									<small class="help-block col-sm-8 col-sm-offset-3">{{ $error }}</small>
								@endforeach
							@endif
						</div>
					@endif
					
					@if (session('user')->is_admin_deca == 1)
						@if ($errors->has('status'))
							<div class="row form-group has-error">
						@else
							<div class="row form-group">
						@endif
						<label class="col-sm-4 col-md-3 control-label">Statut *</label>
						<div class="col-sm-8 col-md-5">
							<select class="form-control" name="status" id="status">
								<option value="">-- S&eacute;lectionner un statut --</option>
									<?php $selectedStatus = '';
										if (isset($Demand->status)) {
											$selectedStatus = $Demand->status;
										}
										else {
											$selectedStatus = "A traiter";
										}
									?>
									<option value="A traiter" {{ ($selectedStatus == 'A traiter') ? 'selected' : '' }}>A traiter</option>
									<option value="En cours" {{ ($selectedStatus == 'En cours') ? 'selected' : '' }}>En cours</option>
									<option value="Clos" {{ ($selectedStatus == 'Clos') ? 'selected' : '' }}>Clos</option>
							</select>
						</div>
						@if ($errors->has('status'))
							@foreach ($errors->get('status') as $error)
								<small class="help-block col-sm-8 col-sm-offset-3">{{ $error }}</small>
							@endforeach
						@endif
						</div>
					@else
						<input type='hidden' name='status' id='status' value="{{$Demand->status or 'A traiter'}}" />
					@endif
					
					
					@if (session('user')->is_admin_deca == 1)
						@if ($errors->has('contact_medium'))
							<div class="row form-group has-error">
						@else
							<div class="row form-group">
						@endif
						<label class="col-sm-4 col-md-3 control-label">Moyen de contact *</label>
						<div class="col-sm-8 col-md-5">
								<input type="text" class="form-control"  name="contact_medium" id="contact_medium" value="{{$Demand->contact_medium or 'Portail'}}" />
						</div>
						@if ($errors->has('contact_medium'))
							@foreach ($errors->get('contact_medium') as $error)
								<small class="help-block col-sm-8 col-sm-offset-3">{{ $error }}</small>
							@endforeach
						@endif
						</div>
					@else
						<input type='hidden' name='contact_medium' id='contact_medium' value="{{$Demand->contact_medium or 'Portail'}}" />
					@endif
					
					@if (session('user')->is_admin_deca == 1)
					<div class="row form-group">
						<label class="col-sm-4 col-md-3 control-label">Priorit&eacute;</label>
						<div class="col-sm-8 col-md-5">
							<select class="form-control" name="priority" id="priority">
								<option value="">-- S&eacute;lectionner une priorit&eacute; --</option>
									<?php $selectedPriority = '';
										if (isset($Demand->priority)) {
											$selectedPriority = $Demand->priority;
										}
										else {
											$selectedPriority = "Basse";
										}
									?>
									<option value="Basse" {{ ($selectedPriority == 'Basse') ? 'selected' : '' }}>Basse</option>
									<option value="Moyenne" {{ ($selectedPriority  == 'Moyenne') ? 'selected' : '' }}>Moyenne</option>
									<option value="Haute" {{ ($selectedPriority  == 'Haute') ? 'selected' : '' }}>Haute</option>
							</select>
						</div>
					</div>
					@else
						<input type='hidden' name='priority' id='priority' value="{{$Demand->priority or 'Basse'}}" />
					@endif
						
					<div class="row form-group">
						<label class="col-sm-4 col-md-3 control-label">Objet *</label>
						<div class="col-sm-8 col-md-6">
							<select class="populate placeholder" name="object_id" id="object_id">
								<option value="">-- S&eacute;lectionner un objet --</option>
								@foreach($caseObjects as $objet)
									<option value="{{ $objet->id }}">{{ $objet->object }}</option>
								@endforeach
							</select>
						</div>
					</div>
					<div class="row form-group">
						<label class="col-sm-4 col-md-3 control-label">Motif *</label>
						<div class="col-sm-8 col-md-6">
							<select class="populate placeholder" name="motive_id" id="motive_id">
								<option value="">-- S&eacute;lectionner un motif --</option>
							</select>
						</div>
					</div>	
					<div class="row form-group">
						<label class="col-sm-3 control-label">Notification SMS</label>
						<div class="col-sm-8">
							<div class="toggle-switch toggle-switch-success">
								<label>
									<input type="checkbox" name="smsNotification" id="smsNotification" value="{{ $Demand->smsNotification or '0'}}" {{ isset($demand->smsNotification) ? 'checked' : '' }} />
									<div class="toggle-switch-inner"></div>
									<div class="toggle-switch-switch"><i class="fa fa-check"></i></div>
								</label>
							</div>
						</div>
					</div>
					<div class="row form-group">
						<label class="col-sm-3 col-md-3 control-label">Commentaires *</label>
						<div class="col-sm-8 col-md-9">
							<textarea rows=8 maxlength=500 class="form-control"  name="comments" id="comments">{{$Demand->comments or ''}}</textarea>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-4">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-user"></i>
					<span>Mes coordonn&eacute;es</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">{{ $account[0]->Salutation or ' ' }} {{ $account[0]->FirstName . " " . $account[0]->LastName }}</h4>
					<div class="row form-group">
						<label class="col-sm-3 control-label">T&eacute;l&eacute;phone</label>
						<div class="col-sm-5">
							{{ $account[0]->Phone or 'non renseign&eacute;' }}
						</div>
					</div>
					<div class="row form-group">
						<label class="col-sm-3 control-label">T&eacute;l&eacute;phone mobile</label>
						<div class="col-sm-5">
							{{ $account[0]->MobilePhone or 'non renseign&eacute;' }}
						</div>
					</div>
					<div class="row form-group">
						<label class="col-sm-3 control-label">Email</label>
						<div class="col-sm-5">
							{{ $account[0]->Email }}
						</div>
					</div>
				</div>
				<div class="card address">
					<h4 class="page-header">Votre adresse</h4>
					<p>
						<span>{{ $account[0]->Adresse__c or ' ' }}</span> <br>
						<span>{{ $account[0]->Code_Postal__c or ' '}}</span>
						<span>{{ $account[0]->Ville__c or ' '}}</span>
						<span>{{ $account[0]->Pays__c or ' '}}</span>
					</p>
				</div>
				<div class="row form-group col-xs-12 col-sm-12 col-md-12">
					<button type="button" id="modify-usercase" class="btn btn-primary" id="modifyCoordCase" onclick='window.location.href="account";'>
						<span>
							<i class="fa fa-pencil-square-o"></i>
							Modifier mes coordonn&eacute;es
						</span>
					</button>
				</div>
			</div>
		</div>
	</div>
	<div class="row form-group col-xs-12 col-sm-8 col-sm-offset-2 col-md-4 col-md-offset-4">
		{!! Form::button('<i class="fa fa-times-circle"></i> Annuler', ['class'=>'btn btn-danger']) !!}
		{!! Form::button('<i class="fa fa-floppy-o"></i> Enregistrer' , ['type' => 'submit', 'class'=>'btn btn-success']) !!}
	</div>
</div>
<script type="text/javascript">
// Run Select2 plugin on elements
function DemoSelect2(){
	$('#motive_id').select2();
	$('#object_id').select2();
}

$(document).ready(function() {
	// Add slider for change test input length
	FormLayoutExampleInputLength($( ".slider-style" ));
	// Add tooltip to form-controls
	$('.form-control').tooltip();
	LoadSelect2Script(DemoSelect2);
	// Load example of form validation
	LoadBootstrapValidatorScript(DemoFormValidator);
	// Add drag-n-drop feature to boxes
	WinMove();
	
	//DialogCase();
	
	$("#object_id").change(function() {
		var $motifs = $("#motive_id");
		$motifs.empty();
		$motifs.append('<option value="" selected="selected">-- S&eacute;lectionner un motif --</option>');
		$motifs.select2();
		
		$.getJSON("getMotifsFromObject/" + $("#object_id").val(), function(data) {
			$.each(data, function(index, value) {
				$motifs.append('<option value="' + index +'">' + value + '</option>');
			});
		});
	});
});
</script>
{!! Form::close() !!}

@endsection

resources/views/demands/edit.blade.php
@extends('layout')

@section('content')
<div id="dialogForm" class="modal fade" role="dialog"></div>
<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="demands">Mes demandes</a></li>
			<li><a href="demands/{{$Demand->external_id or ''}}/edit">Demande n&deg; {{$Demand->external_id or ''}}</a></li>
		</ol>
	</div>
</div>

{!! Form::model($Demand, ['method' => 'PATCH', 'route' => ['demands.update', $Demand->external_id]]) !!}
	{!! csrf_field() !!}
	@include('demands/partials/_form', ['submit_text' => 'Enregistrer'])
{!! Form::close() !!}

<script type="text/javascript">
$(document).ready(function() {
	$("#addComment").on("click", function() {
		$('#dialogForm').load('addComment #dialogPwd', function(responseTxt, statusTxt, xhr){
			$('#dialogForm').modal('show');
			$.getScript('js/addComment.js');
			$('#external_id').val() = {{$Demand->external_id or ''}};
		});
	});
});
</script>

@endsection

resources/views/demands/index.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="demands">Mes demandes</a></li>
			<li><a href="demands">Toutes mes demandes</a></li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-pencil-square-o"></i>
					<span>Mes demandes</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				@if (Session::has('message'))		
					<div class="flash alert-info">			
						<p>{{ Session::get('message') }}</p>		
					</div>	
				@endif
				<button type="button" onclick='window.location.href="{{ route('demands.create') }}";' class="btn btn-primary" id="newCase">
					<span>
						<i class="fa fa-pencil-square-o"></i>
						Nouvelle demande
					</span>
				</button>
				@if ( false )
					<br /><br />Vous n'avez effectu&eacute; aucune demande. Veuillez cliquer sur le bouton "Nouvelle demande" pour initier une nouvelle demande.
				@else
					<table id="tableCase" class="table table-striped table-hover table-heading table-datatable dataTable">
						<thead>
							<tr>
								<th>N&ordm;</th>
								<th>Date de cr&eacute;ation</th>
								<th>Moyen de contact</th>
								<th>Objet</th>
								<th>Motif</th>
								<th>Statut</th>
								<th>Date de cl&ocirc;ture</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						@foreach( $Demands as $Demand )
							@if($Demand->Status == 'Clos')
								<tr style="background-color:limegreen">
							@else
								<tr>
							@endif
								<td><a href='demands/{{ $Demand->external_id or '' }}/edit'>{{ $Demand->external_id or '' }}</a></td>
								<td><?php $dateArray = explode("T", $Demand->created_date); 
									$date = date_format(date_create($dateArray[0]), 'd/m/Y');?>
									{{ $date or ' ' }}</td>
								<td>{{ $Demand->contact_medium or ' ' }}</td>
								<td>{{ $Demand->objectLbl or ' ' }}</td>
								<td>{{ $Demand->motiveLbl or ' ' }}</td>
								<td>{{ $Demand->status or ' ' }}</td>
								<td>
									<?php $dateClos = '';
										if (isset($Demand->closed_date)) {
											$dateClosArray = explode("T", $Demand->closed_date);
											$dateClos = date_format(date_create($dateClosArray[0]), 'd/m/Y');
										}?>
									{{ $dateClos or ' ' }}
								</td>
								<td>
									{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('demands.destroy', $Demand->external_id))) !!}
									{!! Form::button('&nbsp;<i class="fa fa-eye"></i>&nbsp;' , ['title' => 'Visualiser', 'class' => 'btn btn-success editCaseLink', 'value' => $Demand->external_id]) !!}
									@if (session('user')->is_admin_deca == 1)
										{!! Form::button('&nbsp;<i class="fa fa-trash"></i>&nbsp;' , ['title' => 'Supprimer','type' => 'submit', 'class' => 'btn btn-danger']) !!}
									@endif
									{!! Form::close() !!}
								</td>
							</tr>
						@endforeach 
						</tbody>
					</table>
				@endif
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#tableCase').dataTable( {
		language: {
			processing:     "Traitement en cours...",
			search:         "",
			lengthMenu:     "Afficher _MENU_",
			info:           "Demandes _START_ &agrave; _END_ sur _TOTAL_",
			infoEmpty:      "",
			infoFiltered:   "(filtr&eacute; de _MAX_ demandes au total)",
			infoPostFix:    "",
			loadingRecords: "Chargement en cours...",
			zeroRecords:    "Aucune demande &agrave; afficher",
			emptyTable:     "Aucune demande &agrave; afficher",
			paginate: {
				first:      "Premier",
				previous:   "Pr&eacute;c&eacute;dent",
				next:       "Suivant",
				last:       "Dernier"
			},
			aria: {
				sortAscending:  ": activer pour trier la colonne par ordre croissant",
				sortDescending: ": activer pour trier la colonne par ordre décroissant"
			}
		},
		"aaSorting": [[ 0, "asc" ]],
		"sDom": "<'box-content'<'col-sm-6'f><'col-sm-6 text-right'l><'clearfix'>>rt<'box-content'<'col-sm-6'i><'col-sm-6 text-right'p><'clearfix'>>",
	} );
	$('#tableCase_filter input').attr("placeholder", "Rechercher");
	$('#tableCase_filter input').attr("class", "");
	
	$(".editCaseLink").on("click", function(){
		var spinner = new Spinner(opts).spin(target);
		var demand = $(".editCaseLink");
		var url = 'demands/' + demand.val() + '/edit';
		alert(url);
		window.location = url;
	});
});
</script>

@endsection