app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication form
Route::get('auth/login','Auth\AuthController@getLogin');
Route::get('auth/reset','Auth\AuthController@getLoginAfterResetPassword');
Route::post('auth/login','Auth\AuthController@postLogin');
Route::get('auth/logout','Auth\AuthController@getLogout');
//

// Registration form
Route::get('auth/register','Auth\AuthController@getRegister');
Route::post('auth/register','Auth\AuthController@postRegister');
//
// Password reset link request
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
//
// Password reset
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');
Route::post('password/reset/{token}', 'Auth\PasswordController@postReset');

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function() {

	Route::get('home', function() {
		return Redirect::route('demands.index');
	});
	
	// DEBUT Route utilisateurs 
	Route::model('users', 'App\User');
	Route::resource('users', 'UserController');

	Route::bind('users', function($value, $route) {
		return App\User::whereEmail($value)->first();
	});
	
	Route::get('modifyPassword', 'UserController@modifyPassword');
	Route::match(['get', 'post'],'updatePwd', function() {
		return view('users.partials.updatePwd');
	});
	// FIN Route utilisateurs
	
	// DEBUT Routes Mairie
	Route::get('council', function() {
    	return View::make('councils.show')->with('council', Session::get('council'));
	});
	
	Route::model('councils', 'App\Council');
	Route::resource('councils', 'CouncilsController');
	// FIN routes mairie
	
	Route::get('account', function() {
		return view('account');
	});
	
	Route::get('modifyAccount', 'UserController@modifyAccount');
	
	Route::get('addLinkFoyer', 'UserController@addLinkFoyer');
	Route::get('deleteLinkFoyer', 'UserController@deleteLinkFoyer');
	
	Route::get('getAssociation', 'UserController@getAssociation');
	Route::get('addLinkAssociation', 'UserController@addLinkAssociation');
	Route::get('deleteLinkAssociation', 'UserController@deleteLinkAssociation');
	
	Route::match(['get', 'post'],'modifyCoord', function() {
		return view('modifyCoord');
	});
	Route::match(['get', 'post'],'modifyAddress', function() {
		return view('modifyAddress');
	});
	
	Route::match(['get', 'post'],'addLinkFoy', function() {
		return view('addLinkFoy');
	});
	Route::match(['get', 'post'],'addLinkAsso', function() {
		return view('addLinkAsso');
	});
	
	Route::get('editHouseMember', function() {
		return view('editHouseMember');
	});
	
	Route::get('editAssociation', function() {
		return view('editAssociation');
	});

	// DEBUT Route des demandes
	Route::model('demands', 'App\Demand');
	Route::resource('demands', 'DemandsController');
	Route::bind('demands', function($value, $route) {
		return App\Demand::whereExternalId($value)->first();
	});
	
	// Liste des motifs lies a un objet
	Route::get('getMotifsFromObject/{id}','DemandsController@getMotifsFromObject');
	
	// Ajout d'un commentaire sur une demande
	Route::get('submitComment', 'DemandsController@submitComment');
	Route::match(['get', 'post'],'addComment', function() {
		return view('demands.partials.addComment');
	});
	// FIN Route des demandes
	
	// Route des evenements
	Route::get('events', function() {
		return view('events');
	});
	
	//Admin
	Route::get('admin', function() {
		return view('admin');
	});

	Route::get('admin2', function() {
		return view('admin2');
	});	

	Route::get('admin3', function() {
		return view('admin2');
	});	

	Route::get('admin4', function() {
		return view('admin2');
	});	

	Route::get('admin5', function() {
		return view('admin2');
	});	
	Route::get('admin6', function() {
		return view('admin2');
	});	
	Route::group(['middleware' => 'admin'], function() {
		Route::model('portalConfigs', 'App\PortalConfig');
		Route::resource('portalConfigs', 'PortalConfigsController');
	});//aaa
	//bbbb
	//cccc
});

app/council.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Council extends Model
{
    /**
    * The database table used by the model.
    *
    * @var string
    */
    protected $table = 'councils';

    /**
    * The attributes that are mass assignable.
    *
    * @var array
    */
    protected $fillable = ['fullname','address','city','zipcode','country','email','landlinephone','logo','website','mayorName','mayorPhone','mayorMobilePhone','mayorEmail','open_hours_id'];

    /**
    * The attributes excluded from the model's JSON form.
    *
    * @var array
    */
    protected $hidden = [];
	
	protected $guarded = [];

    public function openHours()
    {
        return $this->belongsTo('App\openHours');
    }
}

resources/views/councils/create.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="councils">Mairies</a></li>
		</ol>
	</div>
</div>
 
{!! Form::model(new App\Council, ['route' => ['councils.store']]) !!}
	{!! csrf_field() !!}
    @include('councils/partials/_form', ['submit_text' => 'Sauvegarder'])
{!! Form::close() !!}

@endsection

resources/views/councils/edit.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="councils">Mairies</a></li>
		</ol>
	</div>
</div>

{!! Form::model($council, ['onsubmit' => 'return checkOpenHours();' , 'method' => 'PATCH', 'route' => ['councils.update', $council->id]]) !!}
	{!! csrf_field() !!}
	@include('councils/partials/_form', ['submit_text' => 'Sauvegarder'])
{!! Form::close() !!}

<script type="text/javascript">
function checkOpenHours()
{
	var days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
	var fg = 0;

	for (var cpt = 0; cpt < days.length; cpt++) 
	{
		var AmOpen = $('#' + days[cpt] + 'AmOpen').val();
		var AmClose = $('#' + days[cpt] + 'AmClose').val();
		var PmOpen = $('#' + days[cpt] + 'PmOpen').val();
		var PmClose = $('#' + days[cpt] + 'PmClose').val();

		if ((AmOpen && !AmClose) || (AmClose && !AmOpen))
		{
			$('#' + days[cpt] + 'AmOpen').css({ "border-color" : "red", "border-width" : "thin" });
			$('#' + days[cpt] + 'AmClose').css({ "border-color" : "red", "border-width" : "thin" });

			fg++;
		}

		if ((PmOpen && !PmClose) || (PmClose && !PmOpen))
		{
			$('#' + days[cpt] + 'PmOpen').css({ "border-color" : "red", "border-width" : "thin" });
			$('#' + days[cpt] + 'PmClose').css({ "border-color" : "red", "border-width" : "thin" });

			fg++;
		}
	}

	if (fg == 0)
	{
		return true;
	}
	else
	{
		return false;
	}
}
</script>
@endsection

resources/views/councils/index.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="councils">Mairies</a></li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-home"></i>
					<span>Mairie</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				@if (Session::has('message'))		
					<div class="flash alert-info">			
						<p>{{ Session::get('message') }}</p>		
					</div>	
				@endif
				@if (session('user')->is_admin_deca == 1)
				<center><button type="button" onclick='window.location.href="{{ route('councils.create') }}";' class="btn btn-primary btn-sm btn-label-left" id="newCouncil"><span><i class="fa fa-pencil-square-o"></i></span>Nouvelle mairie</button></center>
				@endif
				@if ( !$councils->count() )
					Aucune mairie recens&eacute;e. Veuillez cliquer sur le bouton "Nouvelle mairie" pour cr&eacute;er une mairie.
				@else
					<table id="tableCouncil" class="table table-striped table-hover table-heading table-datatable dataTable">
						<thead>
							<tr>
								<th></th>
								<th>Nom</th>
								<th>Adresse</th>
								<th>Code postal</th>
								<th>Ville</th>
								<th>Maire</th>
							</tr>
						</thead>
						<tbody>
						@foreach( $councils as $council )
							<tr>
								<td>
									{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('councils.destroy', $council->id))) !!}
									{!! link_to_route('councils.edit', 'Modifier', array($council->id), array('class' => 'btn btn-info')) !!}
									@if (session('user')->is_admin_deca == 1)
									{!! Form::submit('Supprimer', array('class' => 'btn btn-danger')) !!}
									@endif
									{!! Form::close() !!}
								</td>
								<td>{{ $council->fullname or ''}}</td>
								<td>{{ $council->address or '' }}</td>
								<td>{{ $council->zipcode or '' }}</td>
								<td>{{ $council->city or '' }}</td>
								<td>{{ $council->mayorName or '' }}</td>
							</tr>
						@endforeach 
						</tbody>
					</table>
				@endif
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#tableCouncil').dataTable( {
		language: {
			processing:     "Traitement en cours...",
			search:         "",
			lengthMenu:     "Afficher _MENU_",
			info:           "Mairies _START_ &agrave; _END_ sur _TOTAL_",
			infoEmpty:      "",
			infoFiltered:   "(filtr&eacute; de _MAX_ mairies au total)",
			infoPostFix:    "",
			loadingRecords: "Chargement en cours...",
			zeroRecords:    "Aucune mairie &agrave; afficher",
			emptyTable:     "Aucune mairie &agrave; afficher",
			paginate: {
				first:      "Premier",
				previous:   "Pr&eacute;c&eacute;dent",
				next:       "Suivant",
				last:       "Dernier"
			},
			aria: {
				sortAscending:  ": activer pour trier la colonne par ordre croissant",
				sortDescending: ": activer pour trier la colonne par ordre décroissant"
			}
		},
		"aaSorting": [[ 0, "asc" ]],
		"sDom": "<'box-content'<'col-sm-6'f><'col-sm-6 text-right'l><'clearfix'>>rt<'box-content'<'col-sm-6'i><'col-sm-6 text-right'p><'clearfix'>>",
	} );
	$('#tableCouncil_filter input').attr("placeholder", "Rechercher");
	$('#tableCouncil_filter input').attr("class", "");
});
</script>

@endsection

resources/views/councils/show.blade.php
@extends('layout')

@section('content')

<style type="text/css">
  html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
</style>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmKGzyoTvJMdOJ6hC25saSHF2RF-cSyyI">
</script>
<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="#">Ma mairie</a></li>
			<li><a href="council">{{ $council->fullname or '' }}</a></li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-8">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-home"></i>
					<span>Ma mairie</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">{{$council->fullname or ''}}</h4>
						<div class="row form-group">
							<label class="col-sm-3 control-label">T&eacute;l&eacute;phone</label>
							<div class="col-sm-5">
								{{$council->landlinephone or ''}}
							</div>
						</div>
						<div class="row form-group">
							<label class="col-sm-3 control-label">Email</label>
							<div class="col-sm-5">
								<a href="mailto:{{$council->email or ''}}">{{$council->email or ''}}</a>
							</div>
						</div>
						<div class="row form-group">
							<label class="col-sm-3 control-label">Site internet</label>
							<div class="col-sm-5">
								{{$council->website or ''}}
							</div>
						</div>
						<button type="button" onclick='window.location.href="demands/create";' class="btn btn-primary" id="contactUs">
							<span>
								<i class="fa fa-pencil-square-o"></i>
								Nous contacter
							</span>
						</button>
				</div>
				<div class="card address">
					<h4 class="page-header">Adresse de la mairie</h4>
					<p>
						<span>{{$council->address or ''}}</span> <br>
						<span>{{$council->zipcode or ''}}</span>
						<span>{{$council->city or ''}}</span>
						<span>{{$council->country or ''}}</span>
					</p>
					<div class="map" id="map-canvas" style="height: 450px;">
					</div>
				</div>
				<br/>
			</div>
		</div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-4">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-clock-o"></i>
					<span>Horaires d'ouvertures</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="open">
					<p>
						<table class="table table-bordered">
							<thead>
								<th class="primary" style="text-align:center">Jours</th>
								<th class="primary" style="text-align:center" colspan="2">Horaires</th>
							</thead>
							<tbody>
								<tr>
									<td class="primary">Lundi</td>
									<td id="mondayAm" class="alert-danger" style="text-align:center"></td>
									<td id="mondayPm" class="alert-danger" style="text-align:center"></td>
								</tr>
								<tr>
									<td class="primary">Mardi</td>
									<td id="tuesdayAm" class="alert-danger" style="text-align:center"></td>
									<td id="tuesdayPm" class="alert-danger" style="text-align:center"></td>
								</tr>
								<tr>
									<td class="primary">Mercredi</td>
									<td id="wednesdayAm" class="alert-danger" style="text-align:center"></td>
									<td id="wednesdayPm" class="alert-danger" style="text-align:center"></td>
								</tr>
								<tr>
									<td class="primary">Jeudi</td>
									<td id="thursdayAm" class="alert-danger" style="text-align:center"></td>
									<td id="thursdayPm" class="alert-danger" style="text-align:center"></td>
								</tr>
								<tr>
									<td class="primary">Vendredi</td>
									<td id="fridayAm" class="alert-danger" style="text-align:center"></td>
									<td id="fridayPm" class="alert-danger" style="text-align:center"></td>
								</tr>
								<tr>
									<td class="primary">Samedi</td>
									<td id="saturdayAm" class="alert-danger" style="text-align:center"></td>
									<td id="saturdayPm" class="alert-danger" style="text-align:center"></td>
								</tr>
								<tr>
									<td class="primary">Dimanche</td>
									<td id="sundayAm" class="alert-danger" style="text-align:center"></td>
									<td id="sundayPm" class="alert-danger" style="text-align:center"></td>
								</tr>
							</tbody>
						</table>
					</p>
				</div>
				<div id="divOpenHours" class="flash" style="text-align:center">			
					<p id="pOpenHours"></p>		
				</div>
			</div>
		</div>
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-user"></i>
					<span>Maire</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<h4 class="page-header">{{$council->mayorName or ''}}</h4>
				<div class="row form-group">
					<label class="col-sm-4 control-label">T&eacute;l&eacute;phone</label>
					<div class="col-sm-4">
						{{$council->mayorPhone or ''}}
					</div>
				</div>
				<div class="row form-group">
					<label class="col-sm-4 control-label">T&eacute;l&eacute;phone mobile</label>
					<div class="col-sm-4">
						{{$council->mayorMobilePhone or ''}}
					</div>
				</div>
				<div class="row form-group">
					<label class="col-sm-4 control-label">Email</label>
					<div class="col-sm-4">
						<a href="mailto:{{$council->mayorEmail or ''}}">{{$council->mayorEmail or ''}}</a>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>
<script>
function initialize() {
var geocoder = new google.maps.Geocoder();
var mapOptions = {
    scaleControl: true,
	zoom: 15,
    center: {lat: -34.397, lng: 150.644}
  };
  
var  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

var address = "{{$council->address or ''}}," + " " + "{{$council->city or ''}}," + " " + "{{$council->zipcode or ''}}";
geocoder.geocode( { 'address': address}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      $('#map-canvas').html("La carte n'a pas pu s'afficher, veuillez v&eacute;rifier l'adresse.");
    }
 });
}
google.maps.event.addDomListener(window, 'load', initialize);

$(document).ready(function() 
{
	/* A OPTIMISER */
	var mondayAmOpen	 = "<?php echo $council->openHours->mondayAmOpen 	 ? $council->openHours->mondayAmOpen		: '' ?>";
	var mondayAmClose	 = "<?php echo $council->openHours->mondayAmClose 	 ? $council->openHours->mondayAmClose	: '' ?>";
    var mondayPmOpen	 = "<?php echo $council->openHours->mondayPmOpen 	 ? $council->openHours->mondayPmOpen		: '' ?>";
    var mondayPmClose	 = "<?php echo $council->openHours->mondayPmClose 	 ? $council->openHours->mondayPmClose	: '' ?>";
    var tuesdayAmOpen	 = "<?php echo $council->openHours->tuesdayAmOpen 	 ? $council->openHours->tuesdayAmOpen	: '' ?>";
    var tuesdayAmClose	 = "<?php echo $council->openHours->tuesdayAmClose 	 ? $council->openHours->tuesdayAmClose	: '' ?>";
    var tuesdayPmOpen	 = "<?php echo $council->openHours->tuesdayPmOpen 	 ? $council->openHours->tuesdayPmOpen	: '' ?>";
    var tuesdayPmClose	 = "<?php echo $council->openHours->tuesdayPmClose 	 ? $council->openHours->tuesdayPmClose	: '' ?>";
    var wednesdayAmOpen	 = "<?php echo $council->openHours->wednesdayAmOpen	 ? $council->openHours->wednesdayAmOpen	: '' ?>";
    var wednesdayAmClose = "<?php echo $council->openHours->wednesdayAmClose ? $council->openHours->wednesdayAmClose	: '' ?>";
    var wednesdayPmOpen	 = "<?php echo $council->openHours->wednesdayPmOpen  ? $council->openHours->wednesdayPmOpen	: '' ?>";
    var wednesdayPmClose = "<?php echo $council->openHours->wednesdayPmClose ? $council->openHours->wednesdayPmClose	: '' ?>";
    var thursdayAmOpen	 = "<?php echo $council->openHours->thursdayAmOpen 	 ? $council->openHours->thursdayAmOpen	: '' ?>";
    var thursdayAmClose	 = "<?php echo $council->openHours->thursdayAmClose  ? $council->openHours->thursdayAmClose	: '' ?>";
    var thursdayPmOpen	 = "<?php echo $council->openHours->thursdayPmOpen 	 ? $council->openHours->thursdayPmOpen	: '' ?>";
    var thursdayPmClose	 = "<?php echo $council->openHours->thursdayPmClose  ? $council->openHours->thursdayPmClose	: '' ?>";
    var fridayAmOpen	 = "<?php echo $council->openHours->fridayAmOpen 	 ? $council->openHours->fridayAmOpen		: '' ?>";
    var fridayAmClose	 = "<?php echo $council->openHours->fridayAmClose 	 ? $council->openHours->fridayAmClose	: '' ?>";
    var fridayPmOpen	 = "<?php echo $council->openHours->fridayPmOpen 	 ? $council->openHours->fridayPmOpen		: '' ?>";
    var fridayPmClose	 = "<?php echo $council->openHours->fridayPmClose 	 ? $council->openHours->fridayPmClose	: '' ?>";
    var saturdayAmOpen	 = "<?php echo $council->openHours->saturdayAmOpen 	 ? $council->openHours->saturdayAmOpen	: '' ?>";
    var saturdayAmClose	 = "<?php echo $council->openHours->saturdayAmClose  ? $council->openHours->saturdayAmClose	: '' ?>";
    var saturdayPmOpen	 = "<?php echo $council->openHours->saturdayPmOpen 	 ? $council->openHours->saturdayPmOpen	: '' ?>";
    var saturdayPmClose	 = "<?php echo $council->openHours->saturdayPmClose  ? $council->openHours->saturdayPmClose	: '' ?>";
    var sundayAmOpen	 = "<?php echo $council->openHours->sundayAmOpen 	 ? $council->openHours->sundayAmOpen   	: '' ?>";
    var sundayAmClose	 = "<?php echo $council->openHours->sundayAmClose 	 ? $council->openHours->sundayAmClose	: '' ?>";
    var sundayPmOpen	 = "<?php echo $council->openHours->sundayPmOpen 	 ? $council->openHours->sundayPmOpen		: '' ?>";
    var sundayPmClose	 = "<?php echo $council->openHours->sundayPmClose 	 ? $council->openHours->sundayPmClose	: '' ?>";
    /**/

    var days = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

	for (var cpt = 0; cpt < days.length; cpt++) 
	{
		var AmOpen = eval(days[cpt] + "AmOpen").substr(0, 5);
		var AmClose = eval(days[cpt] + "AmClose").substr(0, 5);
		var PmOpen = eval(days[cpt] + "PmOpen").substr(0, 5);
		var PmClose = eval(days[cpt] + "PmClose").substr(0, 5);

		if (AmOpen != '' && AmClose != '')
		{ 
			$('#' + days[cpt] + 'Am').html(AmOpen + " - " + AmClose);
			$('#' + days[cpt] + 'Am').switchClass('alert-danger', 'alert-success'); 
		}

		if (PmOpen != '' && PmClose != '')
		{ 
			$('#' + days[cpt] + 'Pm').html(PmOpen + " - " + PmClose);
			$('#' + days[cpt] + 'Pm').switchClass('alert-danger', 'alert-success'); 
		}

		var today = new Date();
	
		if (cpt == today.getDay())
		{
			var now = today.getTime();
			var year = today.getFullYear();
			var month = today.getMonth();
			var day = today.getDate();

			var dAmOpenA  = AmOpen  ? new Date(year, month, day, AmOpen.split(":")[0] - 1, 	AmOpen.split(":")[1], 	0) : null;
			var dAmOpen   = AmOpen 	? new Date(year, month, day, AmOpen.split(":")[0], 		AmOpen.split(":")[1], 	0) : null;
			var dAmCloseA = AmClose ? new Date(year, month, day, AmClose.split(":")[0] - 1, AmClose.split(":")[1], 	0) : null;
			var dAmClose  = AmClose ? new Date(year, month, day, AmClose.split(":")[0], 	AmClose.split(":")[1], 	0) : null;
			var dPmOpenA  = PmOpen 	? new Date(year, month, day, PmOpen.split(":")[0] - 1, 	PmOpen.split(":")[1], 	0) : null;
			var dPmOpen   = PmOpen 	? new Date(year, month, day, PmOpen.split(":")[0], 		PmOpen.split(":")[1], 	0) : null;
			var dPmCloseA = PmClose ? new Date(year, month, day, PmClose.split(":")[0] - 1, PmClose.split(":")[1], 	0) : null;
			var dPmClose  = PmClose ? new Date(year, month, day, PmClose.split(":")[0], 	PmClose.split(":")[1],	0) : null;

			if ((dAmOpen && now >= dAmOpen.getTime() && dAmCloseA && now < dAmCloseA.getTime()) || 
				(dPmOpen && now >= dPmOpen.getTime() && dPmCloseA && now < dPmCloseA.getTime()))
			{
				$('#divOpenHours').addClass('alert-success'); 
				$('#pOpenHours').html("Actuellement Ouverte");
			}
			else if ((dAmOpen && now >= dAmOpenA.getTime() && now < dAmOpen.getTime()) || 
					 (dPmOpen && now >= dPmOpenA.getTime() && now < dPmOpen.getTime())) 
			{
				var delay = (now < dAmOpen.getTime()) ? dAmOpen.getTime() - now : dPmOpen.getTime() - now;

				$('#divOpenHours').addClass('alert-warning'); 
				$('#pOpenHours').html("Ouvre dans " + (new Date(delay).getMinutes() + 1) + " minute(s)");
			}
			else if ((dAmClose && now >= dAmCloseA.getTime() && now < dAmClose.getTime()) ||
					 (dPmClose && now >= dPmCloseA.getTime() && now < dPmClose.getTime()))
			{
				var delay = (now < dAmClose.getTime()) ? dAmClose.getTime() - now : dPmClose.getTime() - now;
	
				$('#divOpenHours').addClass('alert-warning'); 
				$('#pOpenHours').html("Ferme dans " + (new Date(delay).getMinutes() + 1) + " minute(s)");
			}
			else
			{
				$('#divOpenHours').addClass('alert-danger'); 
				$('#pOpenHours').html("Actuellement Fermée");
			}
		}
	}
});
</script>
@stop