app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication form
Route::get('auth/login','Auth\AuthController@getLogin');
Route::get('auth/reset','Auth\AuthController@getLoginAfterResetPassword');
Route::post('auth/login','Auth\AuthController@postLogin');
Route::get('auth/logout','Auth\AuthController@getLogout');
//

// Registration form
Route::get('auth/register','Auth\AuthController@getRegister');
Route::post('auth/register','Auth\AuthController@postRegister');
//
// Password reset link request
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
//
// Password reset
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');
Route::post('password/reset/{token}', 'Auth\PasswordController@postReset');

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function() {

	Route::get('home', function() {
		return Redirect::route('demands.index');
	});
	
	// DEBUT Route utilisateurs 
	Route::model('users', 'App\User');
	Route::resource('users', 'UserController');

	Route::bind('users', function($value, $route) {
		return App\User::whereEmail($value)->first();
	});
	
	Route::get('modifyPassword', 'UserController@modifyPassword');
	Route::match(['get', 'post'],'updatePwd', function() {
		return view('users.partials.updatePwd');
	});
	// FIN Route utilisateurs
	
	// DEBUT Routes Mairie
	Route::get('council', function() {
    	return View::make('councils.show')->with('council', Session::get('council'));
	});
	
	Route::model('councils', 'App\Council');
	Route::resource('councils', 'CouncilsController');
	// FIN routes mairie
	
	Route::get('account', function() {
		return view('account');
	});
	
	Route::get('modifyAccount', 'UserController@modifyAccount');
	
	Route::get('addLinkFoyer', 'UserController@addLinkFoyer');
	Route::get('deleteLinkFoyer', 'UserController@deleteLinkFoyer');
	
	Route::get('getAssociation', 'UserController@getAssociation');
	Route::get('addLinkAssociation', 'UserController@addLinkAssociation');
	Route::get('deleteLinkAssociation', 'UserController@deleteLinkAssociation');
	
	Route::match(['get', 'post'],'modifyCoord', function() {
		return view('modifyCoord');
	});
	Route::match(['get', 'post'],'modifyAddress', function() {
		return view('modifyAddress');
	});
	
	Route::match(['get', 'post'],'addLinkFoy', function() {
		return view('addLinkFoy');
	});
	Route::match(['get', 'post'],'addLinkAsso', function() {
		return view('addLinkAsso');
	});
	
	Route::get('editHouseMember', function() {
		return view('editHouseMember');
	});
	
	Route::get('editAssociation', function() {
		return view('editAssociation');
	});

	// DEBUT Route des demandes
	Route::model('demands', 'App\Demand');
	Route::resource('demands', 'DemandsController');
	Route::bind('demands', function($value, $route) {
		return App\Demand::whereExternalId($value)->first();
	});
	
	// Liste des motifs lies a un objet
	Route::get('getMotifsFromObject/{id}','DemandsController@getMotifsFromObject');
	
	// Ajout d'un commentaire sur une demande
	Route::get('submitComment', 'DemandsController@submitComment');
	Route::match(['get', 'post'],'addComment', function() {
		return view('demands.partials.addComment');
	});
	// FIN Route des demandes
	
	// Route des evenements
	Route::get('events', function() {
		return view('events');
	});
	
	//Admin
	Route::get('admin', function() {
		return view('admin');
	});

	Route::get('admin2', function() {
		return view('admin2');
	});	

	Route::get('admin3', function() {
		return view('admin2');
	});	

	Route::get('admin4', function() {
		return view('admin2');
	});	

	Route::get('admin5', function() {
		return view('admin2');
	});	
	Route::get('admin6', function() {
		return view('admin2');
	});	
	Route::group(['middleware' => 'admin'], function() {
		Route::model('portalConfigs', 'App\PortalConfig');
		Route::resource('portalConfigs', 'PortalConfigsController');
	});//aaa
	//bbbb
	//cccc
});

app/portalConfig.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class portalConfig extends Model
{
    /**
	* The database table used by the model.
	*
	* @var string
	*/
	protected $table = 'portal_configs';

	/**
	* The attributes that are mass assignable.
	*
	* @var array
	*/
	protected $fillable = ['council_id','config_key','config_label','config_value','config_marker','config_comments','activated','council_enabled','council_activated'];

	/**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];
	
	protected $guarded = [];
}

resources/views/portalconfigs/create.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="./home">Accueil</a></li>
			<li><a href="./portalConfigs">Configuration</a></li>
		</ol>
	</div>
</div>

{!! Form::model(new App\PortalConfig, ['route' => ['portalConfigs.store']]) !!}
	{!! csrf_field() !!}
    @include('portalConfigs/partials/_form', ['submit_text' => 'Enregistrer'])
{!! Form::close() !!}

@endsection

resources/views/portalconfigs/edit.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="./home">Accueil</a></li>
			<li><a href="./portalConfigs">Configuration</a></li>
		</ol>
	</div>
</div>

{!! Form::model($portalConfig, ['method' => 'PATCH', 'route' => ['portalConfigs.update', $portalConfig->id]]) !!}
	{!! csrf_field() !!}
	@include('portalConfigs/partials/_form', ['submit_text' => 'Enregistrer'])
{!! Form::close() !!}

@endsection

resources/views/portalconfigs/index.blade.php
@extends('layout')

@section('content')
<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="home">Accueil</a></li>
			<li><a href="portalConfigs">Configuration</a></li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-xs-12">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-cog"></i>
					<span>Configuration</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				@if (Session::has('message'))		
					<div class="flash alert-info">			
						<p>{{ Session::get('message') }}</p>		
					</div>	
				@endif
				@if (session('user')->is_admin_deca == 1)
				<center><button type="button" onclick='window.location.href="{{ route('portalConfigs.create') }}";' class="btn btn-primary btn-sm btn-label-left" id="newPortalConfig"><span><i class="fa fa-pencil-square-o"></i></span>Nouvelle variable</button></center>
				@endif
				@if ( !$portalConfigs->count() )
					Aucune variable recens&eacute;e. Veuillez cliquer sur le bouton "Nouvelle variable" pour cr&eacute;er une variable.
				@else
					<table id="tableConfig" class="table table-striped table-hover table-heading table-datatable dataTable">
						<thead>
							<tr>
								<th></th>
								<th>Variable</th>
								<th>Valeur</th>
								<th>Active</th>
								<th>Aide</th>
								@if (session('user')->is_admin_deca == 1)
									<th>Marker</th>
									<th>Active Decacity</th>
								@endif
							</tr>
						</thead>
						<tbody>
						@foreach( $portalConfigs as $portalConfig )
							<tr>
								<td>
									{!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('portalConfigs.destroy', $portalConfig->id))) !!}
									{!! link_to_route('portalConfigs.edit', 'Modifier', array($portalConfig->id), array('class' => 'btn btn-info')) !!}
									@if (session('user')->is_admin_deca == 1)
										{!! Form::submit('Supprimer', array('class' => 'btn btn-danger')) !!}
									@endif
									{!! Form::close() !!}
								</td>
								<td>{{ $portalConfig->config_key or ''}}</td>
								<td>{{ $portalConfig->config_value or '' }}</td>
								<td>{{ $portalConfig->council_activated or '' }}</td>
								<td><i class="fa fa-comment" title="{{ $portalConfig->config_comments or '' }}"></i></td>
								@if (session('user')->is_admin_deca == 1)
									<td>{{ $portalConfig->config_marker or '' }}</td>
									<td>{{ $portalConfig->activated or '' }}</td>
								@endif
							</tr>
						@endforeach 
						</tbody>
					</table>
				@endif
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
		$('#tableConfig').dataTable( {
		language: {
			processing:     "Traitement en cours...",
			search:         "",
			lengthMenu:     "Afficher _MENU_",
			info:           "Variables _START_ &agrave; _END_ sur _TOTAL_",
			infoEmpty:      "",
			infoFiltered:   "(filtr&eacute; de _MAX_ variables au total)",
			infoPostFix:    "",
			loadingRecords: "Chargement en cours...",
			zeroRecords:    "Aucune variable &agrave; afficher",
			emptyTable:     "Aucune variable &agrave; afficher",
			paginate: {
				first:      "Premier",
				previous:   "Pr&eacute;c&eacute;dent",
				next:       "Suivant",
				last:       "Dernier"
			},
			aria: {
				sortAscending:  ": activer pour trier la colonne par ordre croissant",
				sortDescending: ": activer pour trier la colonne par ordre décroissant"
			}
		},
		"aaSorting": [[ 0, "asc" ]],
		"sDom": "<'box-content'<'col-sm-6'f><'col-sm-6 text-right'l><'clearfix'>>rt<'box-content'<'col-sm-6'i><'col-sm-6 text-right'p><'clearfix'>>",
	} );
	$('#tableConfig_filter input').attr("placeholder", "Rechercher");
	$('#tableConfig_filter input').attr("class", "");
});
</script>

@endsection

resources/views/portalconfigs/show.blade.php
@extends('layout')

@section('content')

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<ol class="breadcrumb">
			<li><a href="./home">Accueil</a></li>
			<li><a href="./portalConfigs">Configuration</a></li>
		</ol>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-12 col-md-8">
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-cog"></i>
					<span>Configuration</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<div class="card">
					<h4 class="page-header">Variable</h4>
					<p>
						<div class="form-group">
							<label class="col-sm-3 control-label">Variable</label>
							<div class="col-sm-5">
								{{$portalConfig->config_key or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Valeur</label>
							<div class="col-sm-5">
								{{$portalConfig->config_value or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Libell&eacute;</label>
							<div class="col-sm-5">
								{{$portalConfig->config_label or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Commentaires</label>
							<div class="col-sm-5">
								{{$portalConfig->config_comments or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Marker</label>
							<div class="col-sm-5">
								{{$portalConfig->config_marker or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Variable activ&eacute;e Decacity</label>
							<div class="col-sm-5">
								{{$portalConfig->activated or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Variable Modifiable mairie</label>
							<div class="col-sm-5">
								{{$portalConfig->council_enabled or ''}}
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-3 control-label">Variable activ&eacute;e</label>
							<div class="col-sm-5">
								{{$portalConfig->council_activated or ''}}
							</div>
						</div>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
@stop